### ISSUE TITLE
Add FLAC & WAV Audio Support 

### ISSUE THREAD

**Issue by sageandpine** [sageandpine/triad-audio-player#1]
#### Description
The current iteration of TRIAD audio player only works with one file type: MP3. This is due to the audio engine TRIAD is using from the  **Pygame** library, which is limited to MP3's. Want to expand TRIAD to support FLAC & WAV audio formats by using more expansive audio engines and python libraries. **Pydub** is  a promising library that seems to meet the necessary requirements to accomplish this task. 

#### Files
main.py

#### Tasks
- [ ] Import Pydub library
- [ ] Refactor/Rewrite Play function to accept WAV and FLAC
- [ ] Refactor/Rewrite ALL Core functions to accept WAV and FLAC
